blocks_n_rows: 5
blocks_n_cols: 8

st_blocks_params:
  maxCorners: 100
  qualityLevel: 0.001
  minDistance: 5
  blockSize: 10

st_global_params:
  maxCorners: 3000
  qualityLevel: 0.001
  minDistance: 5
  blockSize: 20

lk_params:
  flags: 8  # cv.OPTFLOW_LK_GET_MIN_EIGENVALS
  minEigThreshold: 0.0007
